theme: jekyll-theme-architect

title: 土土野蛮人

avatar: https://avatars3.githubusercontent.com/u/5228203?s=400&u=db64aa519ec86d94b3333e515c068a5f0184fa49&v=4

footer-links:
  email: mayaming1983@gmail.com
  linkedin: mayaming1983@gmail.com